name: Check and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    uses: greenbone/workflows/.github/workflows/lint-python.yml@main
    with:
      lint-packages: gvm tests
      python-version: ${{ matrix.python-version }}

  test:
    name: Run tests
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    uses: greenbone/workflows/.github/workflows/test-python.yml@main
    with:
      python-version: ${{ matrix.python-version }}

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v2
        with:
          python-version: "3.10"
          cache: "true"

  build-docs:
    name: Build the documentation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v2
        with:
          cache: "true"
      - name: Build docs
        run: |
          cd docs
          poetry run make html

  versioning:
    name: Check versioning
    uses: greenbone/workflows/.github/workflows/check-version.yml@main
