name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: Linting
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v3
      - name: Check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v1
        with:
          packages: gvm tests
          version: ${{ matrix.python-version }}

  test:
    name: Unit tests
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
        with:
          version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: poetry run python -m unittest

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v1
        with:
          version: 3.8

  build-docs:
    name: Build the documentation
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
        with:
          version: 3.8
      - name: Build docs
        run: |
          cd docs
          poetry run make html
